# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/axl/Downloads/babel-2014-champi_d

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/axl/Downloads/babel-2014-champi_d

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/axl/Downloads/babel-2014-champi_d/CMakeFiles /home/axl/Downloads/babel-2014-champi_d/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/axl/Downloads/babel-2014-champi_d/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f Nina/build/CMakeFiles/doc.dir/build.make Nina/build/CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named doxygen

# Build rule for target.
doxygen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doxygen
.PHONY : doxygen

# fast build rule for target.
doxygen/fast:
	$(MAKE) -f Nina/build/CMakeFiles/doxygen.dir/build.make Nina/build/CMakeFiles/doxygen.dir/build
.PHONY : doxygen/fast

#=============================================================================
# Target rules for targets named echo_server

# Build rule for target.
echo_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 echo_server
.PHONY : echo_server

# fast build rule for target.
echo_server/fast:
	$(MAKE) -f Nina/build/CMakeFiles/echo_server.dir/build.make Nina/build/CMakeFiles/echo_server.dir/build
.PHONY : echo_server/fast

#=============================================================================
# Target rules for targets named nina

# Build rule for target.
nina: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nina
.PHONY : nina

# fast build rule for target.
nina/fast:
	$(MAKE) -f Nina/build/CMakeFiles/nina.dir/build.make Nina/build/CMakeFiles/nina.dir/build
.PHONY : nina/fast

#=============================================================================
# Target rules for targets named nina_unit_test

# Build rule for target.
nina_unit_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nina_unit_test
.PHONY : nina_unit_test

# fast build rule for target.
nina_unit_test/fast:
	$(MAKE) -f Nina/build/CMakeFiles/nina_unit_test.dir/build.make Nina/build/CMakeFiles/nina_unit_test.dir/build
.PHONY : nina_unit_test/fast

#=============================================================================
# Target rules for targets named sock_acceptor

# Build rule for target.
sock_acceptor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sock_acceptor
.PHONY : sock_acceptor

# fast build rule for target.
sock_acceptor/fast:
	$(MAKE) -f Nina/build/CMakeFiles/sock_acceptor.dir/build.make Nina/build/CMakeFiles/sock_acceptor.dir/build
.PHONY : sock_acceptor/fast

#=============================================================================
# Target rules for targets named sock_connector

# Build rule for target.
sock_connector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sock_connector
.PHONY : sock_connector

# fast build rule for target.
sock_connector/fast:
	$(MAKE) -f Nina/build/CMakeFiles/sock_connector.dir/build.make Nina/build/CMakeFiles/sock_connector.dir/build
.PHONY : sock_connector/fast

#=============================================================================
# Target rules for targets named Babe

# Build rule for target.
Babe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Babe
.PHONY : Babe

# fast build rule for target.
Babe/fast:
	$(MAKE) -f Babe/CMakeFiles/Babe.dir/build.make Babe/CMakeFiles/Babe.dir/build
.PHONY : Babe/fast

#=============================================================================
# Target rules for targets named Babel

# Build rule for target.
Babel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Babel
.PHONY : Babel

# fast build rule for target.
Babel/fast:
	$(MAKE) -f Application/CMakeFiles/Babel.dir/build.make Application/CMakeFiles/Babel.dir/build
.PHONY : Babel/fast

#=============================================================================
# Target rules for targets named Babe_SpeexCodec

# Build rule for target.
Babe_SpeexCodec: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Babe_SpeexCodec
.PHONY : Babe_SpeexCodec

# fast build rule for target.
Babe_SpeexCodec/fast:
	$(MAKE) -f Plugin/Codec/CMakeFiles/Babe_SpeexCodec.dir/build.make Plugin/Codec/CMakeFiles/Babe_SpeexCodec.dir/build
.PHONY : Babe_SpeexCodec/fast

#=============================================================================
# Target rules for targets named Babe_PortAudioAudio

# Build rule for target.
Babe_PortAudioAudio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Babe_PortAudioAudio
.PHONY : Babe_PortAudioAudio

# fast build rule for target.
Babe_PortAudioAudio/fast:
	$(MAKE) -f Plugin/Audio/CMakeFiles/Babe_PortAudioAudio.dir/build.make Plugin/Audio/CMakeFiles/Babe_PortAudioAudio.dir/build
.PHONY : Babe_PortAudioAudio/fast

#=============================================================================
# Target rules for targets named Babe_QtGui

# Build rule for target.
Babe_QtGui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Babe_QtGui
.PHONY : Babe_QtGui

# fast build rule for target.
Babe_QtGui/fast:
	$(MAKE) -f Plugin/Gui/CMakeFiles/Babe_QtGui.dir/build.make Plugin/Gui/CMakeFiles/Babe_QtGui.dir/build
.PHONY : Babe_QtGui/fast

#=============================================================================
# Target rules for targets named Babe_NinaNetwork

# Build rule for target.
Babe_NinaNetwork: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Babe_NinaNetwork
.PHONY : Babe_NinaNetwork

# fast build rule for target.
Babe_NinaNetwork/fast:
	$(MAKE) -f Plugin/Network/CMakeFiles/Babe_NinaNetwork.dir/build.make Plugin/Network/CMakeFiles/Babe_NinaNetwork.dir/build
.PHONY : Babe_NinaNetwork/fast

#=============================================================================
# Target rules for targets named BabelServer

# Build rule for target.
BabelServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BabelServer
.PHONY : BabelServer

# fast build rule for target.
BabelServer/fast:
	$(MAKE) -f Server/CMakeFiles/BabelServer.dir/build.make Server/CMakeFiles/BabelServer.dir/build
.PHONY : BabelServer/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... doc"
	@echo "... doxygen"
	@echo "... echo_server"
	@echo "... nina"
	@echo "... nina_unit_test"
	@echo "... sock_acceptor"
	@echo "... sock_connector"
	@echo "... Babe"
	@echo "... Babel"
	@echo "... Babe_SpeexCodec"
	@echo "... Babe_PortAudioAudio"
	@echo "... Babe_QtGui"
	@echo "... Babe_NinaNetwork"
	@echo "... BabelServer"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

